[package]
name = "lpm-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = { version = "0.9", package = "gtk4" }
glib = "0.10"
sysinfo = "0.28"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lpm-core = { path = "../lpm-core" }

