[package]
name = "lpm-core"
version = "0.1.0"
edition = "2021"

[dependencies]
sysinfo = "=0.28.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
csv = "1.3"
chrono = "0.4.41"
libc = "0.2"

